jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        distribution: temurin
        java-version: 18
    - continue-on-error: true
      name: Build with Maven
      run: mvn install -T 1C -Dmaven.javadoc.skip=true -B -V
name: jdk18
on:
  repository_dispatch:
    types: trigger-ga___maven18.yaml
